import express from "express";
import cors from "cors";
import mysql from "mysql2";
import dotenv from "dotenv";

dotenv.config();

console.log("Starting server...");

const app = express();

app.use(cors());
app.use(express.json());

const db = mysql.createConnection({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
});

db.connect((err) => {
  if (err) {
    console.error("MySQL connection error:", err);
  } else {
    console.log("MySQL Connected");
  }
});

app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

app.get("/employees", (req, res) => {
  db.query("SELECT * FROM employees", (err, result) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }

    res.json(result);
  });
});
app.get("/employees", (req, res) => {
  db.query("SELECT * FROM employees", (err, result) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json(result);
  });
});

// 🌟 ADD THIS NEW POST ROUTE HERE 🌟
app.post("/employees", (req, res) => {
  const { name, email, department } = req.body;

  // Simple validation block
  if (!name || !email || !department) {
    return res.status(400).json({ error: "All fields are required" });
  }

  const queryText = "INSERT INTO employees (name, email, department) VALUES (?, ?, ?)";
  const values = [name, email, department];

  db.query(queryText, values, (err, result) => {
    if (err) {
      console.error("Database entry insertion error:", err.message);
      return res.status(500).json({ error: err.message });
    }

    // Respond with success structure along with the autogenerated MySQL ID
    res.status(201).json({
      message: "Employee added successfully",
      id: result.insertId,
    });
  });
});

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server running on ${PORT}`);
});